// Film & Awards Events Data
// Central source of truth for all events displayed on TrendiMovies

export type EventStatus = 'upcoming' | 'live' | 'past';

export interface FilmEvent {
  id: string;
  name: string;
  shortName: string;
  year: number;
  status: EventStatus;
  startDate: string;
  endDate: string;
  location: string;
  venue: string;
  description: string;
  color: string;
  accentColor: string;
  emoji: string;
  slug: string;
  pageUrl: string;
  categories: string[];
  highlights: string[];
  topAward?: string;
  winner?: string;
  edition?: string;
  // Full per-category results (winner + nominees) for the dedicated event page.
  results?: AwardResult[];
}

export interface AwardResult {
  category: string;
  winner: string;        // "Film" or "Person — Film"
  nominees?: string[];   // other nominees in this category
}

export const filmEvents: FilmEvent[] = [
  {
    id: 'cannes-2026',
    name: 'Cannes Film Festival 2026',
    shortName: 'Cannes 2026',
    year: 2026,
    status: 'past',
    startDate: '2026-05-13',
    endDate: '2026-05-24',
    location: 'Cannes, France',
    venue: 'Palais des Festivals et des Congres',
    description: "The 79th Cannes Film Festival — the most prestigious film festival in the world. The Palme d'Or went to Cristian Mungiu's 'Fjord', presented at the closing ceremony on May 24.",
    color: '#B50C1B',
    accentColor: '#F7D000',
    emoji: '🌴',
    slug: 'cannes-2026',
    pageUrl: '/cannes-2026',
    categories: ["Palme d'Or", 'Grand Prix', 'Jury Prize', 'Best Director', 'Best Actress', 'Best Actor', 'Best Screenplay', "Camera d'Or", 'Special Jury Prize'],
    highlights: ['79th Edition', 'May 13-24, 2026', 'Palais des Festivals, Cannes', 'International Jury presides'],
    topAward: "Palme d'Or",
    winner: "Fjord (Cristian Mungiu)",
    edition: '79th',
  },
  {
    id: 'mtv-2026',
    name: 'MTV Movie & TV Awards 2026',
    shortName: 'MTV Awards 2026',
    year: 2026,
    status: 'upcoming',
    startDate: '2026-06-07',
    endDate: '2026-06-07',
    location: 'Los Angeles, CA',
    venue: 'Peacock Theater',
    description: 'The annual MTV Movie & TV Awards celebrate the best in film and television as voted on by fans worldwide.',
    color: '#FF0033',
    accentColor: '#FFE600',
    emoji: '🎬',
    slug: 'mtv-awards-2026',
    pageUrl: '/event/mtv-awards-2026',
    categories: ['Movie of the Year', 'Best Performance', 'Best Kiss', 'Best Fight', 'Best Hero', 'Best Villain', 'Best Documentary'],
    highlights: ['Fan-voted awards', 'June 7, 2026', 'Los Angeles'],
    topAward: 'Movie of the Year',
    edition: '2026',
  },
  {
    id: 'venice-2026',
    name: 'Venice Film Festival 2026',
    shortName: 'Venice 2026',
    year: 2026,
    status: 'upcoming',
    startDate: '2026-08-26',
    endDate: '2026-09-05',
    location: 'Venice, Italy',
    venue: 'Palazzo del Cinema, Lido di Venezia',
    description: "The 83rd Venice International Film Festival, the world's oldest film festival. The Golden Lion is awarded to the best film in competition.",
    color: '#8B0000',
    accentColor: '#FFD700',
    emoji: '🦁',
    slug: 'venice-2026',
    pageUrl: '/event/venice-2026',
    categories: ['Golden Lion', 'Silver Lion Grand Jury Prize', 'Silver Lion Best Director', 'Volpi Cup Best Actor', 'Volpi Cup Best Actress', 'Special Jury Prize'],
    highlights: ['83rd Edition', 'Aug 26 - Sep 5, 2026', 'Lido di Venezia'],
    topAward: 'Golden Lion',
    edition: '83rd',
  },
  {
    id: 'tiff-2026',
    name: 'Toronto International Film Festival 2026',
    shortName: 'TIFF 2026',
    year: 2026,
    status: 'upcoming',
    startDate: '2026-09-10',
    endDate: '2026-09-20',
    location: 'Toronto, Canada',
    venue: 'TIFF Bell Lightbox',
    description: "TIFF is one of the most influential film festivals in the world and a key launchpad for Oscar season. The People's Choice Award is a bellwether for Best Picture.",
    color: '#E8002D',
    accentColor: '#FFFFFF',
    emoji: '🍁',
    slug: 'tiff-2026',
    pageUrl: '/event/tiff-2026',
    categories: ["People's Choice Award", 'Best Canadian Film', 'Discovery Award', 'NETPAC Award', 'FIPRESCI Prize'],
    highlights: ['51st Edition', 'Sep 10-20, 2026', 'Toronto, Canada'],
    topAward: "People's Choice Award",
    edition: '51st',
  },
  {
    id: 'emmys-2026',
    name: 'Emmy Awards 2026',
    shortName: 'Emmys 2026',
    year: 2026,
    status: 'upcoming',
    startDate: '2026-09-21',
    endDate: '2026-09-21',
    location: 'Los Angeles, CA',
    venue: 'Peacock Theater',
    description: 'The 78th Primetime Emmy Awards honour the best in American prime time television.',
    color: '#6B21A8',
    accentColor: '#D4AF37',
    emoji: '📺',
    slug: 'emmys-2026',
    pageUrl: '/event/emmys-2026',
    categories: ['Outstanding Drama Series', 'Outstanding Comedy Series', 'Outstanding Limited Series', 'Outstanding Lead Actor Drama', 'Outstanding Lead Actress Drama'],
    highlights: ['78th Edition', 'September 21, 2026', 'Los Angeles'],
    topAward: 'Outstanding Drama Series',
    edition: '78th',
  },
  {
    id: 'golden-globes-2027',
    name: 'Golden Globe Awards 2027',
    shortName: 'Golden Globes 2027',
    year: 2027,
    status: 'upcoming',
    startDate: '2027-01-11',
    endDate: '2027-01-11',
    location: 'Beverly Hills, CA',
    venue: 'The Beverly Hilton',
    description: 'The 84th Golden Globe Awards honour excellence in film and television from the 2026 calendar year.',
    color: '#B8860B',
    accentColor: '#FFD700',
    emoji: '🌐',
    slug: 'golden-globes-2027',
    pageUrl: '/event/golden-globes-2027',
    categories: ['Best Motion Picture Drama', 'Best Motion Picture Musical or Comedy', 'Best Animated Feature Film', 'Best Non-English Language Film', 'Best Director'],
    highlights: ['84th Edition', 'January 11, 2027', 'Beverly Hills, CA'],
    topAward: 'Best Motion Picture Drama',
    edition: '84th',
  },
  {
    id: 'oscars-2026',
    name: 'Academy Awards 2026',
    shortName: 'Oscars 2026',
    year: 2026,
    status: 'past',
    startDate: '2026-03-15',
    endDate: '2026-03-15',
    location: 'Hollywood, CA',
    venue: 'Dolby Theatre',
    description: 'The 98th Academy Awards ceremony. One Battle after Another dominated the night taking home Best Picture, Best Director, Best Adapted Screenplay, Best Film Editing, and Best Casting.',
    color: '#D4AF37',
    accentColor: '#FFD700',
    emoji: '🏆',
    slug: 'oscars-2026',
    pageUrl: '/oscars-2026',
    categories: ['Best Picture', 'Best Director', 'Best Actor', 'Best Actress', 'Best Supporting Actor', 'Best Supporting Actress', 'Best Original Screenplay', 'Best Adapted Screenplay'],
    highlights: ['98th Edition', 'March 15, 2026', 'Dolby Theatre, Hollywood'],
    topAward: 'Best Picture',
    winner: 'One Battle after Another',
    edition: '98th',
  },
  {
    id: 'sundance-2026',
    name: 'Sundance Film Festival 2026',
    shortName: 'Sundance 2026',
    year: 2026,
    status: 'past',
    startDate: '2026-01-22',
    endDate: '2026-02-01',
    location: 'Park City, Utah',
    venue: 'Park City venues',
    description: 'The premier festival for independent cinema in the United States. Sundance 2026 showcased groundbreaking independent films and documentaries.',
    color: '#DC2626',
    accentColor: '#F97316',
    emoji: '❄️',
    slug: 'sundance-2026',
    pageUrl: '/event/sundance-2026',
    categories: ['Grand Jury Prize Drama', 'Grand Jury Prize Documentary', 'Audience Award Drama', 'Audience Award Documentary'],
    highlights: ['2026 Edition', 'Jan 22 - Feb 1, 2026', 'Park City, Utah'],
    topAward: 'Grand Jury Prize',
    winner: 'Josephine (Beth de Araújo)',
    edition: '2026',
    results: [
      { category: 'U.S. Grand Jury Prize: Dramatic', winner: 'Josephine — Beth de Araújo' },
      { category: 'U.S. Grand Jury Prize: Documentary', winner: 'Nuisance Bear' },
      { category: 'World Cinema Grand Jury Prize: Dramatic', winner: 'Shame and Money' },
      { category: 'World Cinema Grand Jury Prize: Documentary', winner: 'To Hold a Mountain' },
      { category: 'Audience Award: Dramatic', winner: 'Josephine — Beth de Araújo' },
      { category: 'U.S. Documentary Directing Award', winner: 'J.M. Harper — Soul Patrol' },
      { category: 'Audience Award: NEXT', winner: 'Aanikoobijigan' },
      { category: 'NEXT Special Jury Award', winner: 'TheyDream' },
    ],
  },
  {
    id: 'bafta-2026',
    name: 'BAFTA Film Awards 2026',
    shortName: 'BAFTAs 2026',
    year: 2026,
    status: 'past',
    startDate: '2026-02-22',
    endDate: '2026-02-22',
    location: 'London, UK',
    venue: 'Royal Festival Hall',
    description: 'The 79th BAFTA Film Awards, presented by the British Academy of Film and Television Arts.',
    color: '#1E3A5F',
    accentColor: '#C5A028',
    emoji: '🎭',
    slug: 'bafta-2026',
    pageUrl: '/event/bafta-2026',
    categories: ['Best Film', 'Best Director', 'Best Actor', 'Best Actress', 'Outstanding British Film'],
    highlights: ['79th Edition', 'February 22, 2026', 'Royal Festival Hall, London'],
    topAward: 'Best Film',
    winner: 'One Battle After Another',
    edition: '79th',
    results: [
      { category: 'Best Film', winner: 'One Battle After Another', nominees: ['Hamnet', 'Sinners', 'Sentimental Value', 'The Secret Agent'] },
      { category: 'Director', winner: 'Paul Thomas Anderson — One Battle After Another', nominees: ['Chloé Zhao — Hamnet', 'Ryan Coogler — Sinners', 'Joachim Trier — Sentimental Value'] },
      { category: 'Leading Actress', winner: 'Jessie Buckley — Hamnet', nominees: ['Rose Byrne — If I Had Legs I’d Kick You', 'Renate Reinsve — Sentimental Value'] },
      { category: 'Leading Actor', winner: 'Robert Aramayo — I Swear', nominees: ['Michael B. Jordan — Sinners', 'Wagner Moura — The Secret Agent'] },
      { category: 'Supporting Actress', winner: 'Wunmi Mosaku — Sinners', nominees: ['Teyana Taylor — One Battle After Another'] },
      { category: 'Supporting Actor', winner: 'Sean Penn — One Battle After Another', nominees: ['Stellan Skarsgård — Sentimental Value'] },
      { category: 'Outstanding British Film', winner: 'Hamnet' },
      { category: 'Original Screenplay', winner: 'Sinners' },
      { category: 'Adapted Screenplay', winner: 'One Battle After Another' },
      { category: 'Film Not in the English Language', winner: 'Sentimental Value' },
      { category: 'Cinematography', winner: 'One Battle After Another' },
      { category: 'Original Score', winner: 'Sinners' },
      { category: 'Animated Film', winner: 'Zootropolis 2' },
    ],
  },
  {
    id: 'cannes-2025',
    name: 'Cannes Film Festival 2025',
    shortName: 'Cannes 2025',
    year: 2025,
    status: 'past',
    startDate: '2025-05-13',
    endDate: '2025-05-24',
    location: 'Cannes, France',
    venue: 'Palais des Festivals et des Congres',
    description: 'The 78th Cannes Film Festival, presided over by jury president Juliette Binoche.',
    color: '#B50C1B',
    accentColor: '#F7D000',
    emoji: '🌴',
    slug: 'cannes-2025',
    pageUrl: '/event/cannes-2025',
    categories: ["Palme d'Or", 'Grand Prix', 'Jury Prize', 'Best Director', 'Best Actress', 'Best Actor'],
    highlights: ['78th Edition', 'May 13-24, 2025', 'Cannes, France'],
    topAward: "Palme d'Or",
    winner: 'It Was Just an Accident (Jafar Panahi)',
    edition: '78th',
  },
  {
    id: 'oscars-2025',
    name: 'Academy Awards 2025',
    shortName: 'Oscars 2025',
    year: 2025,
    status: 'past',
    startDate: '2025-03-02',
    endDate: '2025-03-02',
    location: 'Hollywood, CA',
    venue: 'Dolby Theatre',
    description: 'The 97th Academy Awards ceremony. The Brutalist won Best Picture.',
    color: '#D4AF37',
    accentColor: '#FFD700',
    emoji: '🏆',
    slug: 'oscars-2025',
    pageUrl: '/event/oscars-2025',
    categories: ['Best Picture', 'Best Director', 'Best Actor', 'Best Actress'],
    highlights: ['97th Edition', 'March 2, 2025', 'Dolby Theatre'],
    topAward: 'Best Picture',
    winner: 'The Brutalist',
    edition: '97th',
  },
  {
    id: 'berlinale-2026',
    name: 'Berlin International Film Festival 2026',
    shortName: 'Berlinale 2026',
    year: 2026,
    status: 'past',
    startDate: '2026-02-12',
    endDate: '2026-02-22',
    location: 'Berlin, Germany',
    venue: 'Berlinale Palast',
    description: "The 76th Berlin International Film Festival. The Golden Bear for Best Film went to İlker Çatak's 'Yellow Letters'.",
    color: '#8B0000',
    accentColor: '#FFD700',
    emoji: '🐻',
    slug: 'berlinale-2026',
    pageUrl: '/event/berlinale-2026',
    categories: ['Golden Bear', 'Silver Bear Grand Jury Prize', 'Best Director', 'Best Leading Performance', 'Best Supporting Performance'],
    highlights: ['76th Edition', 'Feb 12-22, 2026', 'Berlin, Germany'],
    topAward: 'Golden Bear',
    winner: 'Yellow Letters (İlker Çatak)',
    edition: '76th',
    results: [
      { category: 'Golden Bear (Best Film)', winner: 'Yellow Letters — İlker Çatak' },
      { category: 'Silver Bear Grand Jury Prize', winner: 'Salvation — Emin Alper' },
      { category: 'Silver Bear Jury Prize', winner: 'Queen at Sea — Lance Hammer' },
      { category: 'Best Director', winner: 'Grant Gee — Everyone Digs Bill Evans' },
      { category: 'Best Leading Performance', winner: 'Sandra Hüller — Rose' },
      { category: 'Best Supporting Performance', winner: 'Anna Calder-Marshall & Tom Courtenay — Queen at Sea' },
      { category: 'Best Screenplay', winner: 'Geneviève Dulude-De Celles — Nina Roza' },
      { category: 'Outstanding Artistic Contribution', winner: 'Anna Fitch & Banker White — Yo (Love Is a Rebellious Bird)' },
      { category: 'Documentary Award', winner: 'If Pigeons Turned To Gold — Pepa Lubojacki' },
    ],
  },
  {
    id: 'sxsw-2026',
    name: 'SXSW Film & TV Festival 2026',
    shortName: 'SXSW 2026',
    year: 2026,
    status: 'past',
    startDate: '2026-03-12',
    endDate: '2026-03-18',
    location: 'Austin, Texas',
    venue: 'Austin Convention Center',
    description: "South by Southwest Film & TV Festival 2026. The Narrative Feature jury award went to Graham Parkes' 'Wishful Thinking'.",
    color: '#00B4D8',
    accentColor: '#90E0EF',
    emoji: '🎸',
    slug: 'sxsw-2026',
    pageUrl: '/event/sxsw-2026',
    categories: ['Narrative Feature', 'Documentary Feature', 'Audience Award', 'Special Jury Recognition'],
    highlights: ['2026 Edition', 'Mar 12-18, 2026', 'Austin, Texas'],
    topAward: 'Narrative Feature',
    winner: 'Wishful Thinking (Graham Parkes)',
    edition: '2026',
    results: [
      { category: 'Narrative Feature (Jury)', winner: 'Wishful Thinking — Graham Parkes' },
      { category: 'Headliner Audience Award', winner: 'Over Your Dead Body — Jorma Taccone' },
      { category: 'Special Jury Award (Performance)', winner: 'Susan Kent — The Snake' },
      { category: 'TV Premiere (Audience)', winner: 'Monsters of God' },
      { category: 'Music Video (Audience)', winner: 'OK Go — “Love”' },
      { category: 'Texas Short (Audience)', winner: 'Stalin Boys' },
    ],
  },
  {
    id: 'critics-choice-2026',
    name: "Critics' Choice Awards 2026",
    shortName: "Critics' Choice 2026",
    year: 2026,
    status: 'past',
    startDate: '2026-01-04',
    endDate: '2026-01-04',
    location: 'Santa Monica, CA',
    venue: 'Barker Hangar',
    description: "The 31st Critics' Choice Awards. 'One Battle After Another' won Best Picture along with Best Director and Best Adapted Screenplay.",
    color: '#FBBF24',
    accentColor: '#F59E0B',
    emoji: '⭐',
    slug: 'critics-choice-2026',
    pageUrl: '/event/critics-choice-2026',
    categories: ['Best Picture', 'Best Director', 'Best Actor', 'Best Actress', 'Best Adapted Screenplay'],
    highlights: ['31st Edition', 'Jan 4, 2026', 'Santa Monica, CA'],
    topAward: 'Best Picture',
    winner: 'One Battle After Another',
    edition: '31st',
    results: [
      { category: 'Best Picture', winner: 'One Battle After Another', nominees: ['Hamnet', 'Sinners', 'Frankenstein', 'Sentimental Value', 'Marty Supreme'] },
      { category: 'Best Director', winner: 'Paul Thomas Anderson — One Battle After Another', nominees: ['Ryan Coogler — Sinners', 'Chloé Zhao — Hamnet'] },
      { category: 'Best Actor', winner: 'Timothée Chalamet — Marty Supreme', nominees: ['Michael B. Jordan — Sinners', 'Leonardo DiCaprio — One Battle After Another'] },
      { category: 'Best Actress', winner: 'Jessie Buckley — Hamnet', nominees: ['Rose Byrne — If I Had Legs I’d Kick You', 'Renate Reinsve — Sentimental Value'] },
      { category: 'Best Supporting Actor', winner: 'Jacob Elordi — Frankenstein', nominees: ['Sean Penn — One Battle After Another', 'Stellan Skarsgård — Sentimental Value'] },
      { category: 'Best Supporting Actress', winner: 'Amy Madigan — Weapons', nominees: ['Teyana Taylor — One Battle After Another', 'Wunmi Mosaku — Sinners'] },
      { category: 'Best Adapted Screenplay', winner: 'Paul Thomas Anderson — One Battle After Another' },
      { category: 'Best Original Screenplay', winner: 'Ryan Coogler — Sinners' },
    ],
  },
];

export function getUpcomingEvents(): FilmEvent[] {
  return filmEvents.filter(e => e.status === 'upcoming').sort((a, b) =>
    new Date(a.startDate).getTime() - new Date(b.startDate).getTime()
  );
}

export function getLiveEvents(): FilmEvent[] {
  return filmEvents.filter(e => e.status === 'live');
}

export function getPastEvents(): FilmEvent[] {
  return filmEvents.filter(e => e.status === 'past').sort((a, b) =>
    new Date(b.startDate).getTime() - new Date(a.startDate).getTime()
  );
}

export function getDaysUntil(dateStr: string): number {
  const target = new Date(dateStr);
  const now = new Date();
  target.setHours(0,0,0,0);
  now.setHours(0,0,0,0);
  return Math.ceil((target.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
}
